### ISSUE TITLE
Tests are saved without file extension on Ubuntu

### ISSUE THREAD

**Issue by IlyaMuravjov** [spbu-se/KotlinAutomataConstructor#14]
### Текущее поведение

На Ubuntu при сохранении тестов, добавленных в #12, тесты записываются в файлы без расширения

### Ожидаемое поведение

На Ubuntu при сохранении тестов, добавленных в #12, тесты записываются в файлы со специальным расширением

### Как воспроизвести

1. Создать тесты, меню `Tests` / `Create a set of tests`
2. Сохранить тесты, кнопка `Save`, явно не прописывая расширение вручную
3. Попытаться открыть тесты, кнопка `Load`
4. Не наблюдать только что сохранённых тестов, так как они были сохранены без расширения

### Дополнительный контекст

Аналогичной проблемы нет при сохранении вычислителей, меню `File` / `Save As`

### Окружение

Коммит: `cb09d53dac194251214978111e49209d6a2c188e`
Способ запуска:  Gradle-задача `:run`
ОС: Ubuntu 22.04

**Comment by IgorFilimonov** [comment]
https://github.com/spbu-se/KotlinAutomataConstructor/pull/28
