### ISSUE TITLE
UI elements overlap when viewing transition table/matrix

### ISSUE THREAD

**Issue by IlyaMuravjov** [spbu-se/KotlinAutomataConstructor#18]
### Текущее поведение

UI-элементы накладываются друг на друга при просмотре таблицы и матрицы переходов

1. Параметры `State` частично перекрывают первую строку таблицы 
![image](https://github.com/user-attachments/assets/aba6f0ac-cbd3-4e5d-99b9-6db9fc181913)
2. Тип автомата "Deterministic..." накладывается на названия вкладок "State transition..." и "Adjacency matrix..."
![image](https://github.com/user-attachments/assets/2a1e5e1d-7c28-42c0-924c-f7ef3ea5f51f)
3. Список проблем накладывается на поле для кнопок добавления состояний и переходов
![image](https://github.com/user-attachments/assets/8f0f8c8c-f237-4eb3-b711-256d2ab1c028)

### Ожидаемое поведение

UI-элементы не накладываются друг на друга

### Как воспроизвести

1. Добавить одно состояние в автомат (`Right Click` -> `Add State`)
2. Открыть табличное представление автомата (`State transition table` или `Adjacency matrix`)
3. Уменьшить размер окна (опционально)

### Окружение

Релиз или коммит: fea759c8b194fd8f23d1985ba9567cfae042868e
Способ запуска:  Gradle-задача `:run`
ОС: Ubuntu 22.04

**Comment by IgorFilimonov** [comment]
@IlyaMuravjov По поводу перекрытия таблицы параметрами State: не совсем понятно, как это можно решить, не переделывая полностью внешний вид приложения. Разве что можно сдвигать при открытых параметрах таблицу вправо, но сделает ли это ситуацию лучше -- сложно сказать. К тому же эти параметры можно закрыть кликом по любой из таблиц

**Comment by IgorFilimonov** [comment]
https://github.com/spbu-se/KotlinAutomataConstructor/pull/33
