### ISSUE TITLE
Bad quality of new GIFs in Wiki

### ISSUE THREAD

**Issue by IlyaMuravjov** [spbu-se/KotlinAutomataConstructor#29]
### Проблема

Ужасное качество новых гифок в Wiki
- [ ] https://github.com/spbu-se/KotlinAutomataConstructor/blob/develop/wiki/examples.gif
- [ ] https://github.com/spbu-se/KotlinAutomataConstructor/blob/develop/wiki/testing_panel.gif

### Решение

Заменить гифки на видео или воспользоваться утилитами, позволяющими создать гифки высокого качества

**Comment by IgorFilimonov** [comment]
https://github.com/spbu-se/KotlinAutomataConstructor/pull/33
